# Generated by Django 4.0 on 2021-12-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='LegalForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='legal_forms/')),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.forum')),
                ('message_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.employer')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.chat')),
                ('message_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsappid', models.CharField(blank=True, max_length=50, null=True)),
                ('facebookid', models.CharField(blank=True, max_length=50, null=True)),
                ('instagramid', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
        ),
    ]
