# Generated by Django 4.0 on 2021-12-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalForms',
            new_name='LegalForm',
        ),
    ]
