# Generated by Django 4.0 on 2021-12-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('API', '0003_learnenglish_spanishbusinesses_immigrationhelpdesk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnenglish',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
