# Generated by Django 4.0 on 2021-12-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_learnenglish_applicant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpanishBusinesses',
            new_name='SpanishBusiness',
        ),
    ]
