# Generated by Django 4.0 on 2021-12-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_spanishbusinesses_spanishbusiness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spanishbusiness',
            old_name='bussinesname',
            new_name='businessname',
        ),
    ]
