LOCALITIES = (
("Birmingham, AL","Birmingham, Alabama"),
("Mobile, AL","Mobile, Alabama"),
("Huntsville, AL","Huntsville, Alabama"),
("Montgomery, AL","Montgomery, Alabama"),
("Tuscaloosa, AL","Tuscaloosa, Alabama"),
("Anniston","Anniston"),
("Florence, AL","Florence, Alabama"),
("Auburn, AL","Auburn, Alabama"),
("Decatur, AL","Decatur, Alabama"),
("Dothan, AL","Dothan, Alabama"),
("Gadsden, AL","Gadsden, Alabama"),
("Daphne","Daphne"),
("Anchorage, AK","Anchorage, Alaska"),
("Fairbanks, AK","Fairbanks, Alaska"),
("Phoenix","Phoenix"),
("Tucson, AZ","Tucson, Arizona"),
("Little Rock, AR","Little Rock, Arkansas"),
("Avondale","Avondale"),
("Yuma, AZ","Yuma, Arizona"),
("Prescott Valley","Prescott Valley"),
("Flagstaff, AZ","Flagstaff, Arizona"),
("Lake Havasu City, AZ","Lake Havasu City, Arizona"),
("Sierra Vista, AZ","Sierra Vista, Arizona"),
("Casa Grande, AZ","Casa Grande, Arizona"),
("Fayetteville","Fayetteville"),
("Fort Smith, AR","Fort Smith, Arkansas"),
("Jonesboro, AR","Jonesboro, Arkansas"),
("Conway, AR","Conway, Arkansas"),
("Hot Springs, AR","Hot Springs, Arkansas"),
("Pine Bluff, AR","Pine Bluff, Arkansas"),
("Los Angeles","Los Angeles"),
("San Francisco","San Francisco"),
("San Diego, CA","San Diego, California"),
("Riverside","Riverside"),
("Sacramento, CA","Sacramento, California"),
("San Jose, CA","San Jose, California"),
("Fresno, CA","Fresno, California"),
("Concord, CA","Concord, California"),
("Mission Viejo","Mission Viejo"),
("Bakersfield, CA","Bakersfield, California"),
("Murrieta","Murrieta"),
("Reno, NV","Reno, Nevada"),
("Stockton, CA","Stockton, California"),
("Oxnard, CA","Oxnard, California"),
("Modesto, CA","Modesto, California"),
("Indio","Indio"),
("Lancaster","Lancaster"),
("Victorville","Victorville"),
("Santa Rosa, CA","Santa Rosa, California"),
("Antioch, CA","Antioch, California"),
("Santa Clarita, CA","Santa Clarita, California"),
("Visalia, CA","Visalia, California"),
("Thousand Oaks, CA","Thousand Oaks, California"),
("Santa Barbara, CA","Santa Barbara, California"),
("Salinas, CA","Salinas, California"),
("Vallejo, CA","Vallejo, California"),
("Santa Cruz, CA","Santa Cruz, California"),
("Hemet, CA","Hemet, California"),
("Merced, CA","Merced, California"),
("Fairfield, CA","Fairfield, California"),
("Santa Maria, CA","Santa Maria, California"),
("Simi Valley, CA","Simi Valley, California"),
("Redding, CA","Redding, California"),
("Yuba City, CA","Yuba City, California"),
("Seaside","Seaside"),
("El Centro","El Centro"),
("Turlock, CA","Turlock, California"),
("Gilroy","Gilroy"),
("Chico, CA","Chico, California"),
("Vacaville, CA","Vacaville, California"),
("Hanford, CA","Hanford, California"),
("Tracy, CA","Tracy, California"),
("Napa, CA","Napa, California"),
("Manteca, CA","Manteca, California"),
("Livermore, CA","Livermore, California"),
("Madera, CA","Madera, California"),
("Watsonville, CA","Watsonville, California"),
("Davis, CA","Davis, California"),
("Camarillo, CA","Camarillo, California"),
("Porterville, CA","Porterville, California"),
("Lodi, CA","Lodi, California"),
("Paso Robles","Paso Robles"),
("Petaluma, CA","Petaluma, California"),
("San Luis Obispo, CA","San Luis Obispo, California"),
("Woodland, CA","Woodland, California"),
("Delano, CA","Delano, California"),
("Arroyo Grande","Arroyo Grande"),
("Lompoc, CA","Lompoc, California"),
("Denver","Denver"),
("Colorado Springs, CO","Colorado Springs, Colorado"),
("Fort Collins, CO","Fort Collins, Colorado"),
("Pueblo, CO","Pueblo, Colorado"),
("Grand Junction, CO","Grand Junction, Colorado"),
("Greeley, CO","Greeley, Colorado"),
("Boulder, CO","Boulder, Colorado"),
("Longmont, CO","Longmont, Colorado"),
("Lafayette","Lafayette"),
("Hartford, CT","Hartford, Connecticut"),
("Bridgeport","Bridgeport"),
("New Haven, CT","New Haven, Connecticut"),
("Waterbury, CT","Waterbury, Connecticut"),
("Norwich","Norwich"),
("Danbury, CT","Danbury, Connecticut"),
("Dover, DE","Dover, DE"),
("Miami, FL","Miami, Florida"),
("Tampa","Tampa"),
("Orlando, FL","Orlando, Florida"),
("Jacksonville, FL","Jacksonville, Florida"),
("Sarasota","Sarasota"),
("Cape Coral, FL","Cape Coral, Florida"),
("Palm Bay","Palm Bay"),
("Port St. Lucie, FL","Port St. Lucie, Florida"),
("Palm Coast","Palm Coast"),
("Pensacola, FL","Pensacola, Florida"),
("Kissimmee, FL","Kissimmee, Florida"),
("Bonita Springs, FL","Bonita Springs, Florida"),
("Lakeland, FL","Lakeland, Florida"),
("Tallahassee, FL","Tallahassee, Florida"),
("Winter Haven, FL","Winter Haven, Florida"),
("Fort Walton Beach","Fort Walton Beach"),
("Gainesville, FL","Gainesville, Florida"),
("Deltona, FL","Deltona, Florida"),
("North Port","North Port"),
("Ocala, FL","Ocala, Florida"),
("Sebastian","Sebastian"),
("Spring Hill, FL","Spring Hill, Florida"),
("Panama City, FL","Panama City, Florida"),
("Leesburg","Leesburg"),
("Lady Lake","Lady Lake"),
("Homosassa Springs","Homosassa Springs"),
("St. Augustine, FL","St. Augustine, Florida"),
("Zephyrhills, FL","Zephyrhills, Florida"),
("Sebring","Sebring"),
("Titusville, FL","Titusville, Florida"),
("Atlanta, GA","Atlanta, Georgia"),
("Augusta-Richmond County, GA","Augusta-Richmond County, Georgia"),
("Savannah, GA","Savannah, Georgia"),
("Columbus, GA","Columbus, Georgia"),
("Macon, GA","Macon, Georgia"),
("Warner Robins, GA","Warner Robins, Georgia"),
("Gainesville, GA","Gainesville, Georgia"),
("Athens-Clarke County, GA","Athens-Clarke County, Georgia"),
("Albany, GA","Albany, Georgia"),
("Dalton, GA","Dalton, Georgia"),
("Valdosta, GA","Valdosta, Georgia"),
("Rome, GA","Rome, Georgia"),
("Cartersville, GA","Cartersville, Georgia"),
("Hinesville, GA","Hinesville, Georgia"),
("Brunswick, GA","Brunswick, Georgia"),
("Urban Honolulu, HI","Urban Honolulu, Hawaii"),
("Kailua (Honolulu County)","Kailua (Honolulu County)"),
("Kahului, HI","Kahului, Hawaii"),
("Boise, ID","Boise, Idaho"),
("Nampa, ID","Nampa, Idaho"),
("Idaho Falls, ID","Idaho Falls, Idaho"),
("Pocatello, ID","Pocatello, Idaho"),
("Lewiston, ID","Lewiston, Idaho"),
("Chicago, IL","Chicago, Illinois"),
("St. Louis, MO","St. Louis, Missouri"),
("Rockford, IL","Rockford, Illinois"),
("Round Lake Beach","Round Lake Beach"),
("Peoria, IL","Peoria, Illinois"),
("Springfield, IL","Springfield, Illinois"),
("Champaign, IL","Champaign, Illinois"),
("Bloomington","Bloomington"),
("Kenosha, WI","Kenosha, Wisconsin"),
("Decatur, IL","Decatur, Illinois"),
("Alton, IL","Alton, Illinois"),
("Kankakee, IL","Kankakee, Illinois"),
("DeKalb, IL","DeKalb, Illinois"),
("Elmira, NY","Elmira, New York"),
("Carbondale, IL","Carbondale, Illinois"),
("Cape Girardeau, MO","Cape Girardeau, Missouri"),
("Danville, IL","Danville, Illinois"),
("Indianapolis, IN","Indianapolis, Indiana"),
("Fort Wayne, IN","Fort Wayne, Indiana"),
("South Bend, IN","South Bend, Indiana"),
("Evansville, IN","Evansville, Indiana"),
("Lafayette, IN","Lafayette, Indiana"),
("Elkhart, IN","Elkhart, Indiana"),
("Bloomington, IN","Bloomington, Indiana"),
("Terre Haute, IN","Terre Haute, Indiana"),
("Muncie, IN","Muncie, Indiana"),
("Anderson, IN","Anderson, Indiana"),
("Michigan City","Michigan City"),
("Kokomo, IN","Kokomo, Indiana"),
("Columbus, IN","Columbus, Indiana"),
("Des Moines, IA","Des Moines, Iowa"),
("Davenport, IA","Davenport, Iowa"),
("Cedar Rapids, IA","Cedar Rapids, Iowa"),
("Waterloo, IA","Waterloo, Iowa"),
("Iowa City, IA","Iowa City, Iowa"),
("Sioux City, IA","Sioux City, Iowa"),
("Dubuque, IA","Dubuque, Iowa"),
("Ames, IA","Ames, Iowa"),
("Wichita, KS","Wichita, Kansas"),
("Topeka, KS","Topeka, Kansas"),
("Lawrence, KS","Lawrence, Kansas"),
("Manhattan, KS","Manhattan, Kansas"),
("Louisville/Jefferson County, KY","Louisville/Jefferson County, Kentucky"),
("Lexington-Fayette, KY","Lexington-Fayette, Kentucky"),
("Bowling Green, KY","Bowling Green, Kentucky"),
("Elizabethtown","Elizabethtown"),
("Owensboro, KY","Owensboro, Kentucky"),
("New Orleans, LA","New Orleans, Louisiana"),
("Baton Rouge, LA","Baton Rouge, Louisiana"),
("Shreveport","Shreveport"),
("Lafayette, LA","Lafayette, Louisiana"),
("Houma, LA","Houma, Louisiana"),
("Lake Charles, LA","Lake Charles, Louisiana"),
("Monroe, LA","Monroe, Louisiana"),
("Slidell, LA","Slidell, Louisiana"),
("Mandeville","Mandeville"),
("Alexandria, LA","Alexandria, Louisiana"),
("Hammond, LA","Hammond, Louisiana"),
("Portland, ME","Portland, Maine"),
("Bangor, ME","Bangor, Maine"),
("Lewiston, ME","Lewiston, Maine"),
("Baltimore, MD","Baltimore, Maryland"),
("Aberdeen","Aberdeen"),
("Hagerstown, MD","Hagerstown, Maryland"),
("Frederick, MD","Frederick, Maryland"),
("Waldorf, MD","Waldorf, Maryland"),
("Salisbury, MD","Salisbury, Maryland"),
("Westminster","Westminster"),
("Lexington Park","Lexington Park"),
("Cumberland, MD","Cumberland, Maryland"),
("Boston, MA","Boston, Massachusetts"),
("Springfield, MA","Springfield, Massachusetts"),
("Worcester, MA","Worcester, Massachusetts"),
("Barnstable Town, MA","Barnstable Town, Massachusetts"),
("New Bedford, MA","New Bedford, Massachusetts"),
("Leominster","Leominster"),
("Pittsfield, MA","Pittsfield, Massachusetts"),
("Detroit, MI","Detroit, Michigan"),
("Grand Rapids, MI","Grand Rapids, Michigan"),
("Flint, MI","Flint, Michigan"),
("Lansing, MI","Lansing, Michigan"),
("Ann Arbor, MI","Ann Arbor, Michigan"),
("Kalamazoo, MI","Kalamazoo, Michigan"),
("Muskegon, MI","Muskegon, Michigan"),
("Saginaw, MI","Saginaw, Michigan"),
("South Lyon","South Lyon"),
("Holland, MI","Holland, Michigan"),
("Jackson, MI","Jackson, Michigan"),
("Port Huron, MI","Port Huron, Michigan"),
("Battle Creek, MI","Battle Creek, Michigan"),
("Bay City, MI","Bay City, Michigan"),
("Benton Harbor","Benton Harbor"),
("Midland, MI","Midland, Michigan"),
("Monroe, MI","Monroe, Michigan"),
("Minneapolis","Minneapolis"),
("Duluth, MN","Duluth, Minnesota"),
("St. Cloud, MN","St. Cloud, Minnesota"),
("Rochester, MN","Rochester, Minnesota"),
("Mankato, MN","Mankato, Minnesota"),
("Jackson, MS","Jackson, Mississippi"),
("Gulfport, MS","Gulfport, Mississippi"),
("Hattiesburg, MS","Hattiesburg, Mississippi"),
("Pascagoula, MS","Pascagoula, Mississippi"),
("Kansas City, MO","Kansas City, Missouri"),
("Springfield, MO","Springfield, Missouri"),
("Columbia, MO","Columbia, Missouri"),
("Lee's Summit, MO","Lee's Summit, Missouri"),
("Joplin, MO","Joplin, Missouri"),
("St. Joseph, MO","St. Joseph, Missouri"),
("Jefferson City, MO","Jefferson City, Missouri"),
("Billings, MT","Billings, Montana"),
("Missoula, MT","Missoula, Montana"),
("Great Falls, MT","Great Falls, Montana"),
("Omaha, NE","Omaha, Nebraska"),
("Lincoln, NE","Lincoln, Nebraska"),
("Grand Island, NE","Grand Island, Nebraska"),
("Las Vegas","Las Vegas"),
("Carson City, NV","Carson City, Nevada"),
("Nashua, NH","Nashua, New Hampshire"),
("Manchester, NH","Manchester, New Hampshire"),
("Portsmouth, NH","Portsmouth, New Hampshire"),
("Dover","Dover"),
("Trenton, NJ","Trenton, New Jersey"),
("Atlantic City, NJ","Atlantic City, New Jersey"),
("Vineland, NJ","Vineland, New Jersey"),
("Twin Rivers","Twin Rivers"),
("Villas, NJ","Villas, New Jersey"),
("Albuquerque, NM","Albuquerque, New Mexico"),
("Las Cruces, NM","Las Cruces, New Mexico"),
("Santa Fe, NM","Santa Fe, New Mexico"),
("Los Lunas, NM","Los Lunas, New Mexico"),
("Farmington, NM","Farmington, New Mexico"),
("New York","New York"),
("Buffalo, NY","Buffalo, New York"),
("Rochester, NY","Rochester, New York"),
("Albany","Albany"),
("Poughkeepsie","Poughkeepsie"),
("Syracuse, NY","Syracuse, New York"),
("Binghamton, NY","Binghamton, New York"),
("Utica, NY","Utica, New York"),
("Glens Falls, NY","Glens Falls, New York"),
("Saratoga Springs, NY","Saratoga Springs, New York"),
("Middletown, NY","Middletown, New York"),
("Watertown, NY","Watertown, New York"),
("Kingston, NY","Kingston, New York"),
("Ithaca, NY","Ithaca, New York"),
("Charlotte, NC","Charlotte, North Carolina"),
("Raleigh, NC","Raleigh, North Carolina"),
("Winston-Salem, NC","Winston-Salem, North Carolina"),
("Durham, NC","Durham, North Carolina"),
("Greensboro, NC","Greensboro, North Carolina"),
("Fayetteville, NC","Fayetteville, North Carolina"),
("Asheville, NC","Asheville, North Carolina"),
("Wilmington, NC","Wilmington, North Carolina"),
("Concord, NC","Concord, North Carolina"),
("Hickory, NC","Hickory, North Carolina"),
("Gastonia, NC","Gastonia, North Carolina"),
("High Point, NC","High Point, North Carolina"),
("Burlington, NC","Burlington, North Carolina"),
("Greenville, NC","Greenville, North Carolina"),
("Jacksonville, NC","Jacksonville, North Carolina"),
("Rocky Mount, NC","Rocky Mount, North Carolina"),
("Goldsboro, NC","Goldsboro, North Carolina"),
("New Bern, NC","New Bern, North Carolina"),
("Fargo, ND","Fargo, North Dakota"),
("Bismarck, ND","Bismarck, North Dakota"),
("Grand Forks, ND","Grand Forks, North Dakota"),
("Cleveland, OH","Cleveland, Ohio"),
("Cincinnati, OH","Cincinnati, Ohio"),
("Columbus, OH","Columbus, Ohio"),
("Dayton, OH","Dayton, Ohio"),
("Akron, OH","Akron, Ohio"),
("Toledo, OH","Toledo, Ohio"),
("Youngstown, OH","Youngstown, Ohio"),
("Canton, OH","Canton, Ohio"),
("Lorain","Lorain"),
("Middletown, OH","Middletown, Ohio"),
("Springfield, OH","Springfield, Ohio"),
("Newark, OH","Newark, Ohio"),
("Mansfield, OH","Mansfield, Ohio"),
("Lima, OH","Lima, Ohio"),
("Weirton","Weirton"),
("Oklahoma City, OK","Oklahoma City, Oklahoma"),
("Tulsa, OK","Tulsa, Oklahoma"),
("Norman, OK","Norman, Oklahoma"),
("Lawton, OK","Lawton, Oklahoma"),
("Portland, OR","Portland, Oregon"),
("Eugene, OR","Eugene, Oregon"),
("Salem, OR","Salem, Oregon"),
("Medford, OR","Medford, Oregon"),
("Bend, OR","Bend, Oregon"),
("Corvallis, OR","Corvallis, Oregon"),
("Albany, OR","Albany, Oregon"),
("Grants Pass, OR","Grants Pass, Oregon"),
("Philadelphia, PA","Philadelphia, Pennsylvania"),
("Pittsburgh, PA","Pittsburgh, Pennsylvania"),
("Allentown, PA","Allentown, Pennsylvania"),
("Harrisburg, PA","Harrisburg, Pennsylvania"),
("Lancaster, PA","Lancaster, Pennsylvania"),
("Scranton-Wilkes-Barre, Pennsylvania","Scranton-Wilkes-Barre, Pennsylvania"),
("Reading, PA","Reading, Pennsylvania"),
("York, PA","York, Pennsylvania"),
("Erie, PA","Erie, Pennsylvania"),
("Pottstown, PA","Pottstown, Pennsylvania"),
("State College, PA","State College, Pennsylvania"),
("Altoona, PA","Altoona, Pennsylvania"),
("Lebanon, PA","Lebanon, Pennsylvania"),
("Johnstown, PA","Johnstown, Pennsylvania"),
("Hanover, PA","Hanover, Pennsylvania"),
("Monessen","Monessen"),
("Hazleton, PA","Hazleton, Pennsylvania"),
("Williamsport, PA","Williamsport, Pennsylvania"),
("East Stroudsburg, PA","East Stroudsburg, Pennsylvania"),
("Bloomsburg","Bloomsburg"),
("Uniontown","Uniontown"),
("Chambersburg, PA","Chambersburg, Pennsylvania"),
("San Juan, PR","San Juan, Puerto Rico"),
("Aguadilla","Aguadilla"),
("Ponce, PR","Ponce, Puerto Rico"),
("Arecibo, PR","Arecibo, Puerto Rico"),
("San Germán","San Germán"),
("Mayagüez, PR","Mayagüez, Puerto Rico"),
("Yauco, PR","Yauco, Puerto Rico"),
("Fajardo, PR","Fajardo, Puerto Rico"),
("Juana Díaz, PR","Juana Díaz, Puerto Rico"),
("Guayama, PR","Guayama, Puerto Rico"),
("Florida","Florida"),
("Providence, RI","Providence, Rhode Island"),
("Columbia, SC","Columbia, South Carolina"),
("Charleston","Charleston"),
("Greenville, SC","Greenville, South Carolina"),
("Myrtle Beach","Myrtle Beach"),
("Spartanburg, SC","Spartanburg, South Carolina"),
("Mauldin","Mauldin"),
("Rock Hill, SC","Rock Hill, South Carolina"),
("Florence, SC","Florence, South Carolina"),
("Anderson, SC","Anderson, South Carolina"),
("Sumter, SC","Sumter, South Carolina"),
("Hilton Head Island, SC","Hilton Head Island, South Carolina"),
("Sioux Falls, SD","Sioux Falls, South Dakota"),
("Rapid City, SD","Rapid City, South Dakota"),
("Memphis, TN","Memphis, Tennessee"),
("Nashville-Davidson, TN","Nashville-Davidson, Tennessee"),
("Knoxville, TN","Knoxville, Tennessee"),
("Chattanooga, TN","Chattanooga, Tennessee"),
("Clarksville, TN","Clarksville, Tennessee"),
("Murfreesboro, TN","Murfreesboro, Tennessee"),
("Johnson City, TN","Johnson City, Tennessee"),
("Jackson, TN","Jackson, Tennessee"),
("Cleveland, TN","Cleveland, Tennessee"),
("Morristown, TN","Morristown, Tennessee"),
("Dallas","Dallas"),
("Houston, TX","Houston, Texas"),
("San Antonio, TX","San Antonio, Texas"),
("Austin, TX","Austin, Texas"),
("El Paso, TX","El Paso, Texas"),
("McAllen, TX","McAllen, Texas"),
("Denton","Denton"),
("Corpus Christi, TX","Corpus Christi, Texas"),
("Conroe","Conroe"),
("Lubbock, TX","Lubbock, Texas"),
("Laredo, TX","Laredo, Texas"),
("Killeen, TX","Killeen, Texas"),
("Brownsville, TX","Brownsville, Texas"),
("Amarillo, TX","Amarillo, Texas"),
("Waco, TX","Waco, Texas"),
("College Station","College Station"),
("McKinney, TX","McKinney, Texas"),
("Port Arthur, TX","Port Arthur, Texas"),
("Beaumont, TX","Beaumont, Texas"),
("Harlingen, TX","Harlingen, Texas"),
("Tyler, TX","Tyler, Texas"),
("Odessa, TX","Odessa, Texas"),
("Midland, TX","Midland, Texas"),
("Abilene, TX","Abilene, Texas"),
("Texas City, TX","Texas City, Texas"),
("Wichita Falls, TX","Wichita Falls, Texas"),
("Longview, TX","Longview, Texas"),
("San Angelo, TX","San Angelo, Texas"),
("Temple, TX","Temple, Texas"),
("Texarkana","Texarkana"),
("Lake Jackson","Lake Jackson"),
("Victoria, TX","Victoria, Texas"),
("Sherman","Sherman"),
("San Marcos, TX","San Marcos, Texas"),
("Salt Lake City","Salt Lake City"),
("Ogden","Ogden"),
("Provo","Provo"),
("St. George, UT","St. George, Utah"),
("Logan, UT","Logan, Utah"),
("Burlington, VT","Burlington, Vermont"),
("Washington, DC","Washington, DC"),
("Virginia Beach, VA","Virginia Beach, Virginia"),
("Richmond, VA","Richmond, Virginia"),
("Roanoke, VA","Roanoke, Virginia"),
("Fredericksburg, VA","Fredericksburg, Virginia"),
("Lynchburg, VA","Lynchburg, Virginia"),
("Kingsport, TN","Kingsport, Tennessee"),
("Charlottesville, VA","Charlottesville, Virginia"),
("Blacksburg, VA","Blacksburg, Virginia"),
("Williamsburg, VA","Williamsburg, Virginia"),
("Bristol","Bristol"),
("Winchester, VA","Winchester, Virginia"),
("Harrisonburg, VA","Harrisonburg, Virginia"),
("Staunton","Staunton"),
("Seattle, WA","Seattle, Washington"),
("Spokane, WA","Spokane, Washington"),
("Tri-Cities, WA","Tri-Cities, Washington"),
("Bremerton, WA","Bremerton, Washington"),
("Olympia","Olympia"),
("Marysville, WA","Marysville, Washington"),
("Yakima, WA","Yakima, Washington"),
("Bellingham, WA","Bellingham, Washington"),
("Wenatchee, WA","Wenatchee, Washington"),
("Longview, WA","Longview, Washington"),
("Mount Vernon, WA","Mount Vernon, Washington"),
("Walla Walla, WA","Walla Walla, Washington"),
("Huntington, WV","Huntington, West Virginia"),
("Charleston, WV","Charleston, West Virginia"),
("Wheeling, WV","Wheeling, West Virginia"),
("Morgantown, WV","Morgantown, West Virginia"),
("Parkersburg, WV","Parkersburg, West Virginia"),
("Beckley, WV","Beckley, West Virginia"),
("Milwaukee, WI","Milwaukee, Wisconsin"),
("Madison, WI","Madison, Wisconsin"),
("Appleton, WI","Appleton, Wisconsin"),
("Green Bay, WI","Green Bay, Wisconsin"),
("Racine, WI","Racine, Wisconsin"),
("Eau Claire, WI","Eau Claire, Wisconsin"),
("La Crosse, WI","La Crosse, Wisconsin"),
("Wausau, WI","Wausau, Wisconsin"),
("Oshkosh, WI","Oshkosh, Wisconsin"),
("Sheboygan, WI","Sheboygan, Wisconsin"),
("Janesville, WI","Janesville, Wisconsin"),
("West Bend, WI","West Bend, Wisconsin"),
("Beloit, WI","Beloit, Wisconsin"),
("Fond du Lac, WI","Fond du Lac, Wisconsin"),
("Cheyenne, WY","Cheyenne, Wyoming"),
("Casper, WY","Casper, Wyoming"),
)